services:
  epublangmerger:
    image: drumsergio/epublangmerger:1.1.1
    platform: linux/amd64
    build: .
    container_name: epublangmerger
    ports:
      - "3838:3838"
    restart: unless-stopped
